spring:
  config:
    import: secret.yml
  datasource:
    driver-class-name: org.postgresql.Driver
  application:
    name: jobs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    defaultSchema: public

  logging:
    level:
      org:
        springframework:
          security: DEBUG
          springframework: DEBUG
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
server:
  port: 9090

