spring:
  batch:
    jdbc:
      initialize-schema: never #make it always for the first time to have the tables created
    job:
      enabled: false #means spring will not attempt to run all batch jobs, batch jobs will only run when u trigger it
  config:
    import: secret.yml
  datasource:
    driver-class-name: org.postgresql.Driver
  application:
    name: jobs
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    defaultSchema: public

  logging:
    level:
      org:
        springframework:
          security: DEBUG
          springframework: DEBUG
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
server:
  port: 9090

