spring:
  profiles:
    active: memory
  application:
    name: rent-service
  batch:
    job:
      enabled: false
  logging:
    level:
      org:
        springframework:
          security: DEBUG
          springframework: DEBUG
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
server:
  port: 9090